package com.cloundwisdom.im.common.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.cloundwisdom.im.modules.entry.UserEntry;

import com.cloundwisdom.im.common.greendao.UserEntryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userEntryDaoConfig;

    private final UserEntryDao userEntryDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userEntryDaoConfig = daoConfigMap.get(UserEntryDao.class).clone();
        userEntryDaoConfig.initIdentityScope(type);

        userEntryDao = new UserEntryDao(userEntryDaoConfig, this);

        registerDao(UserEntry.class, userEntryDao);
    }
    
    public void clear() {
        userEntryDaoConfig.clearIdentityScope();
    }

    public UserEntryDao getUserEntryDao() {
        return userEntryDao;
    }

}
