package com.cloundwisdom.im.common.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.cloundwisdom.im.modules.entry.greendao.entry.SignEntry;
import com.cloundwisdom.im.modules.entry.greendao.entry.UserEntry;

import com.cloundwisdom.im.common.greendao.SignEntryDao;
import com.cloundwisdom.im.common.greendao.UserEntryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig signEntryDaoConfig;
    private final DaoConfig userEntryDaoConfig;

    private final SignEntryDao signEntryDao;
    private final UserEntryDao userEntryDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        signEntryDaoConfig = daoConfigMap.get(SignEntryDao.class).clone();
        signEntryDaoConfig.initIdentityScope(type);

        userEntryDaoConfig = daoConfigMap.get(UserEntryDao.class).clone();
        userEntryDaoConfig.initIdentityScope(type);

        signEntryDao = new SignEntryDao(signEntryDaoConfig, this);
        userEntryDao = new UserEntryDao(userEntryDaoConfig, this);

        registerDao(SignEntry.class, signEntryDao);
        registerDao(UserEntry.class, userEntryDao);
    }
    
    public void clear() {
        signEntryDaoConfig.clearIdentityScope();
        userEntryDaoConfig.clearIdentityScope();
    }

    public SignEntryDao getSignEntryDao() {
        return signEntryDao;
    }

    public UserEntryDao getUserEntryDao() {
        return userEntryDao;
    }

}
